name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - DEVOP-32

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 12
    - run: |
        npm install
        npm run all
    - name: Archive test coverage
      uses: actions/upload-artifact@v1
      with:
        name: test-coverage
        path: coverage
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: peachjar/action-install-deploy-tools@v1
      with:
        githubUsername: ${{ secrets.GITHUB_DEPLOY_USER }}
        githubToken: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
    - uses: ./
      with:
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        environment: kauai
        helmChartPath: echo-server/
        helmReleaseName: echo-server
        dockerImage: hashicorp/http-echo
        dockerTag: latest
